package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	PlaylistsCollection              = "playlists"
	AutoGeneratedPlaylistsCollection = "autogeneratedplaylists"
)

type Playlist struct {
	ID         primitive.ObjectID   `bson:"_id,omitempty" json:"id"`
	Title      string               `bson:"title" json:"title"`
	Owner      primitive.ObjectID   `bson:"owner" json:"owner"`
	Items      []primitive.ObjectID `bson:"items" json:"items"`
	Visibility string               `bson:"visibility" json:"visibility"` // "public" | "private" | "auto"
	CreatedAt  time.Time            `bson:"createdAt" json:"createdAt"`
	UpdatedAt  time.Time            `bson:"updatedAt" json:"updatedAt"`
}

type AutoGeneratedPlaylist struct {
	ID    primitive.ObjectID   `bson:"_id,omitempty" json:"id"`
	Title string               `bson:"title" json:"title"`
	Items []primitive.ObjectID `bson:"items" json:"items"`
}
