package scheduler

import (
	"context"
	"log/slog"
	"time"

	"ampli/api/internal/models"

	"github.com/robfig/cron/v3"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// Start registers all cron jobs and starts the scheduler.
func Start(db *mongo.Database) {
	c := cron.New(cron.WithLocation(mustLoadLocation("America/Argentina/Buenos_Aires")))

	// Daily at midnight Argentina time: regenerate auto playlists by category
	c.AddFunc("0 0 * * *", func() { //nolint:errcheck
		generatePlaylistsByCategory(db)
	})

	c.Start()
	slog.Info("scheduler started — daily playlist generation at 00:00 ART")
}

// generatePlaylistsByCategory aggregates the top 20 audios per category
// and upserts them into the AutoGeneratedPlaylists collection.
// Mirrors the TypeScript node-cron job in schedule.ts.
func generatePlaylistsByCategory(db *mongo.Database) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	slog.Info("[CRON] starting playlist generation")

	pipeline := mongo.Pipeline{
		{{Key: "$sort", Value: bson.D{{Key: "likes", Value: -1}}}},
		{{Key: "$group", Value: bson.D{
			{Key: "_id", Value: "$category"},
			{Key: "audios", Value: bson.D{{Key: "$push", Value: "$$ROOT._id"}}},
		}}},
		{{Key: "$project", Value: bson.D{
			{Key: "_id", Value: 1},
			{Key: "audios", Value: bson.D{{Key: "$slice", Value: bson.A{"$audios", 20}}}},
		}}},
	}

	cursor, err := db.Collection(models.AudiosCollection).Aggregate(ctx, pipeline)
	if err != nil {
		slog.Error("[CRON] failed to aggregate", "err", err)
		return
	}
	defer cursor.Close(ctx)

	type categoryResult struct {
		Category string               `bson:"_id"`
		Audios   []interface{}        `bson:"audios"`
	}

	var results []categoryResult
	if err := cursor.All(ctx, &results); err != nil {
		slog.Error("[CRON] failed to decode results", "err", err)
		return
	}

	for _, item := range results {
		_, err := db.Collection(models.AutoGeneratedPlaylistsCollection).UpdateOne(
			ctx,
			bson.M{"title": item.Category},
			bson.M{"$set": bson.M{"items": item.Audios}},
			options.Update().SetUpsert(true),
		)
		if err != nil {
			slog.Error("[CRON] failed to upsert playlist", "category", item.Category, "err", err)
		}
	}

	slog.Info("[CRON] playlist generation complete", "count", len(results))
}

func mustLoadLocation(name string) *time.Location {
	loc, err := time.LoadLocation(name)
	if err != nil {
		slog.Warn("failed to load timezone, using UTC", "tz", name, "err", err)
		return time.UTC
	}
	return loc
}
